task_id:"FdDmxqMdWxXShkW0Rk6V5"  check_item:{check_item_id:"_XEA_TSb0pQ1R9p1rVG1B"  command:{command_id:"nYbrznrhdbdm98tsqiCZs"  command_line:"progate diagnose"}}  check_item:{check_item_id:"RMZjXyEpMJCUrm6zFTOy8"  command:{command_id:"b57thp1qeJjHZDfqjBoqr"  command_line:"./new_command/progate_commandline_checker test"}  command:{command_id:"GVPMi_wiU0HJwRSiqKE3q"  command_line:"progate_commandline_checker test"}}  check_item:{check_item_id:"Y-Ys4RrtAABbForrIITiq"  command:{command_id:"lvnL6yea7id3oACfzZJQv"  command_line:"node .progate/judge_process_csv.js"}}  check_item:{check_item_id:"cPPl6aW5WlP9j4cV9_CKN"  command:{command_id:"zNbGbp_f5d35aR-Mi1Epe"  command_line:"node .progate/judge_find.js"}}